= 第四章  表达式

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

:toc:
:toc-placement!:

toc::[]

# 基础
表达式由一个或多个 *运算对象（operand）* 组成，对表达式求值将得到一个结果。
字面值和变量是最简单的 *表达式（expression）*，其结果就是字面值和变量的值。
把一个 *运算符（operator）* 和多个运算对象组合起来就可以生成复杂的表达式。

## 基本概念
根据运算对象的个数划分：
    . 一元运算符：取地址符（&），解引用符（`*`）
    . 二元运算符：相等运算符（==），相乘（`*`）
    . 三元运算符：opr1 ? opr2 : opr3

组合运算符和运算对象：
    . *优先率（precedence）*
    . *结合律（associativity）*
    . 运算对象的 *求值顺序（order of evaaluation）*

运算对象类型转换：小整数型通常会被提升为大整数型。

重载运算符：
    . C++语言定义了运算符作用于内置类型和复合类型的运算对象时所执行的操作。
    . 当运算符作用于类类型的运算对象时，用户可以自定义其含义————*重载运算符（overloaded operator）*

左值和右值：
    . 当对象被用作右值的时候，用的是对象的值（内容）；当对象被用作左值的时候，用的是对象的身份（在内存中的位置）。
    . 不同的运算符对运算对象的要求各不相同，有的需要左值运算对象，有的需要右值运算对象；返回值也有差异，有的得到左值结果，有的得到右值结果。（需要右值的地方可以使用左值来代替，反之不可）
        .. 赋值运算符需要一个（非常量）左值作为其左侧运算对象，得到的结果仍然是一个左值；
        .. 取地址符作用于一个左值运算对象，返回一个指向该运算对象的指针，该指针是个右值；
        .. 内置解引用运算符、下标运算符、迭代器解引用运算符、string和vector的下标运算符的求值结果都是左值。
        .. 内置类型和迭代器的递增递减运算符作用于左值运算对象，所得的结果也是左值。
        .. 如果表达式的求值结果是左值，decltype作用于该表达式（不是变量）得到一个引用类型

[source,c++]
----
int i = 42, *p = &i , &r = i;
decltype(r) a      //错误：a是int&，必须初始化
decltype(r + 0) b; //正确：加法的结果是int，y绑定到变量x
decltype(*p) c;    //错误：c是int&，必须初始化（因为该表达式*p的求值结果可以作为一条赋值语句的左值）
decltype(i) d;     //正确：d是一个（未初始化的）int
decltype((i))) e;  //错误：e是int&，必须初始化
----

WARNING: decltype((variable)) (注意是双层括号)的结果永远是引用，而decltype(variable)结果只有variable本身就是一个引用时才是引用。