= 第六章  函数
:toc:
:toc-placement!:

toc::[]

# 函数基础

函数是一个命名了的代码块。

*函数定义*：返回类型，函数名，形参列表（parameter list），函数体。形参以逗号分隔开，位于一对圆括号之内。

*调用运算符*：执行函数。调用运算符的形式是一对圆括号，作用于一个表达式（函数或指向函数的指针），圆括号内是实参列表（argument list）。

*函数的调用* 完成两项工作：

 . 实参初始化形参（需要一一对应初始化，实参是形参的初始值，需要类型匹配）
 . 将控制权转移给被调用函数

函数调用过程中，当遇到第一条 *return语句* 时函数结束执行过程，return语句也类似的完成两项工作：

                        . 返回return语句中的值（如果有的话）
                        . 将控制权从调用函数转移回主调函数

[source,c++]
----
///编写函数 阶乘
// 返回类型 函数名 (形参列表) {函数体}
int fact(int val){
    int ret = 1;
    while(val > 1){
        ret *= val--;
    }
    return ret;
}

///调用函数
//main()是主调函数
int main(){
    //函数的调用fact(5)，()是调用运算符，5是实参，初始化形参val
    int j = fact(5);
    return 0;
}
----

*函数的形参列表*
[source,c++]
----
void f1(){/* */}     //隐式地定义空形参列表
void f2(void){/* */} //显式地定义空形参列表 与C兼容
----

*函数的返回类型* 一种特殊地返回类型是 void，表示函数不返回任何值；函数的返回类型不能是数组/函数类型，可以是指向数组的指针或函数的指针。

## 局部对象
C++中，名字有作用域，对象有生命周期：

    * 名字的作用域是程序文本的一部分，名字在其中可见。
    * 对象的生命周期是程序执行过程中该对象存在的一段时间。

*局部变量* 函数体是一个语句块，块构成一个新的作用域，则形参和函数体内定义的变量统称为局部变量。它们对于函数而言是“局部”的，仅在函数作用域可见，同时局部变量还会隐藏在外层作用域中同名的其他所有声明中。

局部变量的生命周期依赖于其定义的方式：

    * *自动对象* 对于普通局部变量对应的对象来说，当函数的控制路径经过变量定义语句时创建该对象，当到达定义所在的块末尾时销毁它。我们把只存在于块执行期间的对象称为自动对象（automatic object）。形参是一种自动对象。
    * *局部静态对象* 定义为static类型，其生命周期贯穿于函数调用及之后的时间。局部静态对象在程序的执行路径第一次经过对象定义语句时初始化，并且直到程序终止才销毁。

[source,c++]
----
//该函数统计自己被调用多少次
size_t count_ctrs(){
    //调用结束后，ctr仍然有效。
    static size_t ctr = 0;
    return ++ctr;
}

int main(){
    for(size_t i = 0; i != 1; ++i){
        cout << count_ctrs() << endl;
    }
    return 0;
}
----

## 函数声明
与其他名字一样，函数名也必须在使用前声明。类似于变量，函数只能定义一次，但可以声明多次。

*函数三要素（返回类型，函数名，形参类型）* 描述了函数的接口，说明了调用该函数所需的全部信息。所以函数声明只需提供这三要素即可，将函数定义中的函数体用分号代替。形参名也可省略。函数声明也称之为函数原型（function prototype）。函数可在头文件中声明而在源文件中定义。

## 分离式编译 
分离式编译（separate compilation）允许我们把程序分割到几个文件中去，每个文件独自编译，然后链接多个源文件。

# 参数传递
形参类型决定了形参和实参的交互方式.

## 传引用参数
引用形参是它绑定对象的别名，即实参被 *引用传递*。

    * 使用引用可以避免拷贝：拷贝大的类类型对象比较低效，甚至有的类类型（包括IO类型在内）根本不支持拷贝操作，此时只能通过引用形参访问该类型对象。
    * 使用引用形参可以返回额外信息：一个函数只能返回一个值，而引用提供了返回多个结果的有效途径。
    * 当无需改变引用形参的值时，最好声明为常量引用。
        ** 不能将const对象，字面值或者需要类型转换的对象传递给普通的引用形参。

## 传值参数
实参的值被拷贝给形参，此时形参与实参是两个相互独立的对象，即实参被 *值传递*。

    * 指针形参：指针可以间接访问它所指对象。

## const形参和实参

顶层const与底层const：

    * *顶层const* 作用于对象本身（顶层const可以表示任意的对象是常量），当实参初始化形参时会忽略形参顶层const
    * *底层const* 则与指针和引用等复合类型的基本类型部分相关 
        ** 可以使用非常量初始化一个底层const对象，反之不可，因为类型不匹配，复制后不能改变底层const相应的对象值，不然语法互相矛盾
        ** 一个普通的引用必须用同类型的对象初始化

[source,c++]
----
///
int i = 0;
int *const p1 = &i;         //指针本身是一个常量————顶层const，不能改变p1的值
const int ci = 42;
const int *p2 = &ci;        //指针所指的对象是一个常量————底层const，可以改变p2的值
const int *const p3 = p2;   //靠右的const是顶层const，靠右的是底层const
const int &r = ci;          //用于声明引用的const都是底层const

int *p = p3;                //错误
p2 = p3;                    //正确
p2 = &i;                    //正确
int &r = ci;                //错误 普通的int&不能绑定到int常量上
const int &r2 = i;          //正确 

///
int i = 42;
const int *cp = &i;         //正确 但cp不能改变i
const int &r = i;           //正确 但r不能改变i
const int &r1 = 42;         //正确

int *p = cp;                //错误 p的类型和cp类型不匹配
int &r2 = r;                //错误 类型不匹配
int &r3 = 42;               //错误 不能用字面值初始化一个非常量引用
----



## 数组形参
数组的两个特殊性质：

    * 不允许拷贝数组：无法以值传递的方式使用数组参数
    * 使用数组时（通常）会将其转化成指向数组首元素的指针，数组大小对函数调用没有影响

[source,c++]
----
//三个等价的print函数，形参均为const int*
void print(const int*);
void print(const int[]);
void print(const int[10]);
----

### 数组引用形参
数组的元素应为对象，因此 *不存在引用的数组*，自然也 *不存在引用的数组形参*：
[source,c++]
----
print(int &arr[10]); //错误：将arr声明成了引用的数组（从右往左）
print(int (&arr)[10]); //正确：arr是具有10个整数的整型数组的引用（从内往外）

print(int (&arr)[10]){
    for(auto e: arr){
        cout<< e <<endl;
    }
}

int i = 0, j[2] = {0,1};
int k[10] = {0,1,2,3,4,5,6,7,8,9};
print(&i);//错误
print(j);//错误
print(k);//正确：实参是含有10个整数的数组
----

### 传递多维数组
C++语言中实际上没有真正的多维数组，所谓多维数组其实是 *数组的数组*。而数组的数组，其首元素本身是一个数组，*数组首元素的指针* 就是一个 *指向数组元素的指针*。数组第二维（以及后面所有维度）的大小都是数组类型的一部分，不能省略。
[source,c++]
----
//matrix指向数组的首元素，该数组的元素是由10个整数构成的数组
void print(int (*matrix)[10], int rowSize){/* */}
//等价定义
void print(int matrix[][10], int rowSize){/* */}

//注意区分，括号不可少
int *matrix[10]; //10个指针构成的数组，从右往左阅读，离变量名最近的符号对变量的类型具有最直接的影响。
int (*matrix)[10]; //指向含有10个整数构成的数组
----

### main：处理命令行选项
给main传递实参，用户通过设置一组选项来确定函数所要执行的操作。假定main函数位于可执行文件 https://github.com/Erkaman/hole_fixer[hole_fixer] 之内，命令行如下：
`hole_fixer -in bunnyhole.off -out out.off -outfaces 8000 -upsample 2`
这些命令行选项通过两个（可选的）形参传递给main函数：
[source,c++]
----
//第二个形参 argv 是一个数组，它的元素指向C风格字符串的指针；第一个形参 argc 表示字符串的数量
//argv为命令行选项，argc自动赋值为n+1，n为argv字符串个数，空格分隔，\0结尾。argv[0]保存程序的名字，而非用户输入
int main(int argc, char *argv[]){...}

//因为第二个形参为数组，故可等价定义为
int main(int argc, char **argv){...}
----

以上面提供的命令行为例：
```
argc = 10
argv[0] = "hole_fixer";
argv[1] = "-in";
argv[2] = "bunnyhole.off";
... ...
argv[9] = "2";
argv[10] = 0;
```

在 Visual Studio 中为了能使用这两个参数将信息传入 main 函数，可在 Visual Studio 中设置，设置方式如下：

    * 菜单Project -> Properties -> Configuration Properties -> Debugging
    * 在Command Arguments里填上即可。

### 含有可变形参的函数
*initializer_list形参* ： 用于函数的实参数量未知但全部实参类型相同时的情况。
initializer_list是一种标准库类型，用于表示某种特殊类型的值的数组。

[cols = ">.^, >.^" , options = "header"]
|===
2+^.^|表6.1 initializer_list提供的操作
|initializer_list<T> lst; | 默认初始化；T类型的空列表
|initializer_list<T> lst{a,b,c...} | lst的元素数量等于初始值数量；lst的元素是对应初始值的副本；列表中的元素是const
|lst2(lst) , lst2 = lst | 拷贝或赋值一个initializer_list对象不会拷贝列表中的元素；拷贝后，原始列表和副本共享元素
|lst.size() , lst.begin() , lst.end()|lst中的元素数量，返回指向lst中首元素指针，尾元素下一位置的指针
|===

[source,c++]
----
//调试系统可能有个名为ErrCode的类表示不同类型的错误
void error_msg(ErrCode e, initializer_list<string> il){
    cout<<e.msg()<<": ";
    for(const auto &elem: il){
        cout<<elem<<" ";
    }
    cout<<endl;
}

void main(){
    string expected = "expected", actual = "actual";
    if(expected != actual){
        error_msg(ErrCode(42),{"functionX", expected, actual});
    }else{
        error_msg(ErrCode(0),{"functionX", "okay"});
    }
}
----

*省略符形参*

# 返回类型和return语句


# 函数重载


# 特殊用途语言特性


# 函数指针匹配


# 函数指针


# 小结




