= 第十六章  模板和泛型编程
ifdef::env-github[]
:imagesdir:
 https://gist.githubusercontent.com/path/to/gist/revision/dir/with/all/images
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./
endif::[]
:toc:
:toc-placement!:

toc::[]

# 定义模板

* 面向对象编程（OOP）和泛型编程都能处理编写程序时不知道类型的情况
** 面向对象编程（OOP）能处理在程序运行之前类型都未知的情况
** 泛型编程在编译在编译之时就能获知类型，常见例子: 标准库中的容器（ `vector, set, map, ...`）、迭代器和算法
*** 模板是C++中泛型编程的基础，一个模板就是一个创建类或函数的蓝图或者说公式

## 函数模板

* *函数模板*（function template）: `template <typename T>`
** 模板定义以关键字 `template`开始，后跟一个 *模板参数列表*（template parameter list）——用尖括号 `<>` 括住的一个或多个模板形参的列表，用逗号分隔，且不能为空
** 当使用模板时，隐式或显式地指定 *模板实参*（template argument），将其绑定到模板参数上

* *实例化函数模板*: 当调用一个函数模板时，编译器用函数实参推断模板参数来 *实例化*（instantiate）一个特定版本的函数。该编译器生成地版本通常称为模板的 *实例*（instantiation）

* *模板类型参数*: `template <typename T, class U> T calc(const T&, const U&)`
** 类型参数相当于类型说明符，可以用来指定函数返回类型或函数的参数类型，以及在函数体内用于变量声明和类型转换
** 类型参数前必须使用关键字 `class` 或者 `typename`，这两个关键字含义相同，可以互换使用和混用。旧的程序只能使用class。

* *非类型模板参数*: `template<unsigned N, unsigned M>`
** 在模板中还可以定义非类型参数（nontype parameter），表示一个值而非一个类型，我们通过一个特定的类型名而非关键字 `class` 或 `typename` 来指定非类型参数
** 非类型模板参数的模板实参必须是常量表达式
** `inline` 和 `constexpr` 的函数模板: `template <typename T> inline T min(const T&, const T&);`

* 模板编译: 大多数编译错误在实例化期间报告

[NOTE]
====
函数模板和类模板成员函数的定义通常放在头文件中
====


[source,c++]
----
///函数模板定义
template <typename T>
int compare(const T &v1, const T &v2){
    if(v1 < v2)return -1;
    if(v2 < v1)return 1;
    return 0;
}

//实例化函数模板
//实例化出 int compare(const int&, const int&)
cout << compare(1,0) << endl; //T is int
//实例化出 int compare(const vector<int>&, const vector<int>&)
vector<int> vec1{1,2,3}, vec2{4,5,6};
cout << compare(vec1,vec2) <<endl; //T is vector<int>


///正确: 返回类型与参数类型相同
template <typename T> 
T foo(T* p){
    T tmp = *p;
    //...
    return tmp;
}


///非类型模板参数
template<unsigned N, unsigned M>
int compare(const char (&p1)[N], const char (&p2)[M]){
    return strcmp(p1,p2);
}
//实例化出 int compare(const char (&p1)[3],const char (&p2)[4])
compare("hi","mom");


///inline和constexpr的函数模板
//正确: inline说明符跟在模板参数列表之后
template <typename T> inline T min(const T&, const T&);
//错误: inline说明符位置不对
inline template <typename T> T min(const T&, const T&);


///为print函数编写模版版本，它接受一个数组的引用，能处理任意大小、任意元素类型的数组
//形参是数组的引用，维度是类型的一部分
void print(int (&arr)[10]){
    for(auto elem: arr)
        cout<< elem<<endl;
}
//print函数的模版版本
template<typename Array>
void print(const Array& arr)
{
	for (const auto& elem : arr)
		cout << elem << endl;
}

char s1[] = "Hello";
int a[] = { 0,1,2 };
vector<int> vec{ 3,4,5 };
string s = "Thanks";

print(s1);
print(a);
print(vec);
print(s);
----

## 类模板



## 模板参数


## 成员模板


## 控制实例化



## 效率与灵活性




# 模板实参推断



# 重载与模板




# 可变模板参数




# 模板特例化



